/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as TermsconditionRouteImport } from './routes/termscondition'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CancellationRouteImport } from './routes/cancellation'
import { Route as IndexRouteImport } from './routes/index'

const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsconditionRoute = TermsconditionRouteImport.update({
  id: '/termscondition',
  path: '/termscondition',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRoute = CancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/termscondition': typeof TermsconditionRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/termscondition': typeof TermsconditionRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/partner': typeof PartnerRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/termscondition': typeof TermsconditionRoute
  '/warehouses': typeof WarehousesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cancellation'
    | '/contact'
    | '/partner'
    | '/privacy'
    | '/terms'
    | '/termscondition'
    | '/warehouses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cancellation'
    | '/contact'
    | '/partner'
    | '/privacy'
    | '/terms'
    | '/termscondition'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/cancellation'
    | '/contact'
    | '/partner'
    | '/privacy'
    | '/terms'
    | '/termscondition'
    | '/warehouses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CancellationRoute: typeof CancellationRoute
  ContactRoute: typeof ContactRoute
  PartnerRoute: typeof PartnerRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TermsconditionRoute: typeof TermsconditionRoute
  WarehousesRoute: typeof WarehousesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termscondition': {
      id: '/termscondition'
      path: '/termscondition'
      fullPath: '/termscondition'
      preLoaderRoute: typeof TermsconditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation': {
      id: '/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof CancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CancellationRoute: CancellationRoute,
  ContactRoute: ContactRoute,
  PartnerRoute: PartnerRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TermsconditionRoute: TermsconditionRoute,
  WarehousesRoute: WarehousesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
